posts:
  2023:
    May:
      - title: "AI in the news"
        ref: "posts/2023/May/ai-in-the-news.md"
        tags: ["culture","news"]
      - title: "Testing LLAMA AI chat versions"
        ref: "posts/2023/May/llama-cpp-tests.md"
        tags: ["technology"]
      - title: "May the 4th be with you"
        ref: "posts/2023/May/may-the-4th.md"
        tags: ["culture","entertainment"]
        theme: "space"
    April:
      - title: "Bash vs. Powershell"
        ref: "posts/2023/April/bash-vs-powershell.md"
        tags: ["technology"]
      - title: "It's My First Post!"
        ref: "posts/2023/April/first-post.md"
        tags: ["announcement"]
        pinned: true
