name: Auto-commit build changes

on:
  push:
    branches:
      - build

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          path: main
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: build
          path: build
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install dependencies
        run: cd build && npm install
      - name: Build project
        run: cd build && npm run build
      - name: Copy files to public folder
        run: |
          rm -rf main/assets
          cp -r build/dist/* main/
      - name: Commit changes
        run: |
          cd main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-commit build changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}