name: Auto-commit build changes

on:
  push:
    branches:
      - build

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit build changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ./public/build
          git commit -m "Auto-commit build changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}