name: Auto-commit build changes

on:
  push:
    branches:
      - build

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files to public folder
        run: cp -r dist/* public/
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/*
          git commit -m "Auto-commit build changes"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}